# Generated by Django 5.2.7 on 2026-03-27 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_alter_alumno_options_alumno_carnet_and_more'),
        ('Curso', '0004_alter_curso_creditos'),
        ('asignacion_curso', '0001_initial'),
        ('catedratico', '0002_alter_catedratico_options_remove_catedratico_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacioncurso',
            options={'ordering': ['curso', 'alumno'], 'verbose_name': 'Asignación de Curso', 'verbose_name_plural': 'Asignaciones de Cursos'},
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='alumno',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Alumno.alumno', verbose_name='Alumno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='aula',
            field=models.CharField(default=1, max_length=50, verbose_name='Aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='cupo',
            field=models.PositiveIntegerField(default=40, verbose_name='Cupo máximo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asignacioncurso',
            name='catedratico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='catedratico.catedratico', verbose_name='Catedrático'),
        ),
        migrations.AlterField(
            model_name='asignacioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Curso.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='asignacioncurso',
            name='horario',
            field=models.CharField(max_length=100, verbose_name='Horario'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacioncurso',
            unique_together={('curso', 'alumno')},
        ),
    ]
