# Generated by Django 5.2.7 on 2026-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0005_alumno_alumno_nombre_idx_alumno_alumno_activo_idx_and_more'),
        ('Curso', '0004_alter_curso_creditos'),
        ('asignacion_curso', '0002_alter_asignacioncurso_options_asignacioncurso_alumno_and_more'),
        ('catedratico', '0002_alter_catedratico_options_remove_catedratico_nombre_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asignacioncurso',
            index=models.Index(fields=['alumno'], name='asig_alumno_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncurso',
            index=models.Index(fields=['catedratico'], name='asig_catedratico_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacioncurso',
            index=models.Index(fields=['curso'], name='asig_curso_idx'),
        ),
    ]
