# Generated by Django 4.2.28 on 2026-03-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inscripcion_alumno', '0001_initial'),
        ('asignacion_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionalumno',
            name='asignacion_curso',
            field=models.ManyToManyField(to='asignacion_curso.asignacioncurso'),
        ),
    ]
