# Generated by Django 5.2.7 on 2026-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_alter_alumno_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='carnet',
            field=models.CharField(default='0000000000', help_text='Número de carné de 10 dígitos', max_length=10, unique=True, verbose_name='Carné'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='enrolled_at',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
