# Generated by Django 5.2.7 on 2026-03-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_alter_alumno_options_alumno_carnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='carnet',
            field=models.CharField(blank=True, help_text='Número de carné de 10 dígitos', max_length=10, null=True, unique=True, verbose_name='Carné'),
        ),
    ]
