# Generated by Django 5.2.7 on 2026-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0004_alter_alumno_carnet'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['last_name', 'first_name'], name='alumno_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['is_active'], name='alumno_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['carnet'], name='alumno_carnet_idx'),
        ),
    ]
