# Generated by Django 5.2.7 on 2026-03-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catedratico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catedratico',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Catedrático', 'verbose_name_plural': 'Catedráticos'},
        ),
        migrations.RemoveField(
            model_name='catedratico',
            name='nombre',
        ),
        migrations.AddField(
            model_name='catedratico',
            name='email',
            field=models.EmailField(default='sin@email.com', max_length=254, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catedratico',
            name='first_name',
            field=models.CharField(default='Sin nombre', max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catedratico',
            name='last_name',
            field=models.CharField(default='Sin apellido', max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catedratico',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='catedratico',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialidad'),
        ),
    ]
