# Generated by Django 5.2.7 on 2026-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0005_alumno_alumno_nombre_idx_alumno_alumno_activo_idx_and_more'),
        ('Curso', '0004_alter_curso_creditos'),
        ('Notas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['alumno'], name='nota_alumno_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['curso'], name='nota_curso_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['alumno', 'curso'], name='nota_alumno_curso_idx'),
        ),
    ]
