# Generated by Django 5.2.7 on 2026-03-26 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
        ('catedratico', '0002_alter_catedratico_options_remove_catedratico_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveIntegerField(default=0, verbose_name='Créditos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='catedratico.catedratico', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
